### ISSUE TITLE
Fix includes in stable

### ISSUE THREAD

**Issue by pslacerda** [GLYCAM-Web/GMML#86] opened 2019-05-18 08:03 UTC
Hi,

Can you fix the includes in the stable branch? These files need changes:

```
/src/MolecularModeling/overlaps.cc
/src/MolecularModeling/ring_shape_detection.cc b/src/MolecularModeling/ring_shape_detection.cc
/src/MolecularModeling/superimposition.cc
```

**Comment by gitoliver** [comment] 2019-05-18 19:45
Not sure what the specific issue was, but stable was out of date anyway. I've pull from gmml-dev, which is compiling fine and passing tests. Let me know if you have any issues compiling now.

**Comment by pslacerda** [comment] 2019-05-18 21:57
The same errors ocurs on dev, the includes are point to the wrong directory. Maybe your environment has a special setting?

Anyway fix it doesn't render a fine compilation, and the test_instalation.bash accused some missing txt.

**Comment by Lachele** [comment] 2019-05-18 22:39
How are you compiling?  Are you doing it from the gems directory?  I ask because make.sh in gems remakes the Makefile in gmml.  It is also possible to remake the Makefile in gmml directly.  

In any case, we probably need a little more info about how you're trying to compile and the exact nature of the errors you're getting.  The thing you are complaining about - wrong directory - probably shouldn't happen.  So, we think something else must have gone wrong.

**Comment by pslacerda** [comment] 2019-05-19 01:09
I'm trying to compile `gems-dev` and `gmml-dev`  with:

```fish
set -x PYTHON_HOME /usr/include/python3.7m
set -x GEMSHOME /pedro/carb/gems
set -x GEMSMAKEPROCS 4
./make.sh
```

Lots of include errors appears, for instance:
```
In file included from src/GeometryTopology/geometrytopology.cc:1:
src/GeometryTopology/../../includes/GeometryTopology/geometrytopology.hpp:7:10: fatal error: utils.hpp: Arquivo ou diretório inexistente
 #include "utils.hpp"
          ^~~~~~~~~~~
compilation terminated.
```

Theses errors means that (assuming your compilation works fine) your IDE know how to look for header files but the build script doesn't. But the compilation proceeds and `bash ./test_installation.bash` outputs the following:
```
This test should take less than 10 seconds to run on most modern computers.

This test will compare these files:

	updated_pdb.txt      --   this is the file the test should generate
	test_pdb.txt.save    --   this is the file to which it should be identical


Beginning test.



Checking for diffeences between test output and the standard output.


TEST FAILURE:

	The file called updated_pdb.txt was not generated.  This probably means there
	is something terribly wrong with your installation.
	
	Please check the contents of the following files to determine the problem:
	
	testing.log
	testing.error

TEST FAILURE
```

I fixed the includes on `gmml-stable` but the same `TEST FAILURE` happened.

**Comment by pslacerda** [comment] 2019-05-19 01:28
I'm only looking into this because the server was saying "file not found" for the "Download AMBER-Style PDB" button.

Today it is downloading nice, but the resulting PDB is invalid. For instance all chains were renamed all into `a` but the `LINK` records are linking glucoses between chains `A` or `B`.
[structure.pdb.txt](https://github.com/GLYCAM-Web/gmml/files/3194680/structure.pdb.txt)

**Comment by Lachele** [comment] 2019-05-19 01:44
Oh...  My....  This is entirely different code from what is at glycam.org.  We're working really hard to improve it far beyond what is available there.

I'll work on this more in a little while.  Gotta do other stuff.

In the meantime, are you trying to build an Oligosaccharide or a Glycoprotein?

**Comment by pslacerda** [comment] 2019-05-19 02:12
The file contains two chains of an oligosaccharide obtained from PDB (1C58). Whoa no protein or nucleic acid on PDB?!

I really don't know how the PDB is supposed to be, so I inputted as is. Was impressive such result preserving so much original PDB data (even existing some unsafe behaviour that was triggered renaming chains).

I just wanted a corrected named file to use as input for our simulations. I'm don't know that much about oligosaccarides to do it myself.

By the way, how to place a fatty acid and some other organic molecule into the same system? Any tips?

**Comment by Lachele** [comment] 2019-05-19 04:05
So, if I understand you correctly, you want to run a simulation of cycloamylose?  And, you uploaded that PDB file to the PDB Preprocessor?  

Regarding the question of adding other molecules, what exactly do you want to do?  What are you trying to model?

**Comment by pslacerda** [comment] 2019-05-19 04:24
Yes! I tried the PDB Preprocessor and now I'm trying the Carbohydrate Builder, but the Preprocessor seems to do what we need. (Is it the right tool?)

I'm trying simulate the CA26 coupled with some organic compounds. The compounds I'm doing with GAFF. Some people simulated oligosaccharide with GAFF also (eg http://dx.doi.org/10.1016/j.biomaterials.2012.11.024) but I'm looking for Glycam.

For now I'm trying to simply simulate both CA26 and compounds at the same system because I didn't figured yet how to insert the compounds into the CA26. Do you think docking with a regular docking software and use the best poses is alright? I'm also looking further to see if is possible to encapsulate the compounds into CA26 in a simulation.

**Comment by Lachele** [comment] 2019-05-19 05:11
I think you should bring this up on our mailing list(*).  The couple of us who are scientists and who monitor this forum are up to our ears in stuff we need to do.  There are more folks on the mailing list with science backgrounds, and they might have some ideas.  At the very least, they can help you get the residues renamed.  I haven't looked, but they're likely all alpha 1-4 linkages, so most of the residues will have 4GA as their GLYCAM names (except the ends, which are probably 0GA at the non-reducing terminus and maybe ROH at the reducing end).  The PDB Preprocessor at glycam.org was really tuned for proteins, but it handles some carbs.  The new code should do better.  

(*)  https://listserv.uga.edu/cgi-bin/wa?A0=GLYCAM-L

Re the interactions...  you want to insert molecules into the interiors of the helicies?  Docking might work, but you might also consider something like steered molecular dynamics or one of the other biasing methods.  For that, you might want to ask the AMBER list for ideas.  But, if you ask on that list, just say you want to insert a molecule into a helix, at least in the subject line - if you mention sugars or glycam, you'll probably just get me again.  :-)  

Whatever you do to add interacting molecules, take care that you don't significantly alter the conformations of the carbohydrates.  Or, if you do, make sure the new conformations are realistic.  You should be ok if you make your initial structures by holding the carb helices still and moving the other molecules.  In any case, be gentle when you do that, and when you do your first minimization, just so that the system doesn't distort.

If you really want to compile gems and gmml, the simplest way is to use our docker image - https://hub.docker.com/r/glycamweb/gems-gmml    We've been working to simplify the dependencies, but we still have work to do.  It can be hard to diagnose issues like the one you're having because systems can be different in subtle ways.  I had an entirely unrelated problem just now when I tried to compile outside the container.  I can fix that problem, but that probably won't fix your problem.

**Comment by pslacerda** [comment] 2019-05-20 17:19
Very cool! I wonder if the structure on the paper I linked before could be made with the method on this mail (ie choose appropriate atoms and bond the chitosan to salicylic acids)?

https://listserv.uga.edu/cgi-bin/wa?A2=ind1905&L=GLYCAM-L&D=0&P=3767

The I'll try the docker install later this week and then call the guy who knows about this carbohydrate to supervise the renaming.

**Comment by gitoliver** [comment] 2019-05-21 07:19
Hi Pedro,

1c53 is cycloamylose containing a linear sequence of DGlc with a1-4
repeats. Very interesting system. You can rename this to GLYCAM format
easily by renaming the residue from GLC to 4GA, and it will load into tleap
fine.

Note that this PDB file has some quirks. I would grep out just the HETATM
entries. Some of the O6 atoms have multiple entries (it's more labile than
the other hydroxyls) as the C5-C6 bond rotates. For MD I believe choosing
arbitrarily is fine ( I always go with the first entry in these cases), as
it will rotate in the MD anyway. I *assume* that if the O6's position was
essential for the overall structure (fold?), it would have a more definite
position in the crystal structure. If you're concerned about it you can
restrain the rest of the structure and run an MD to see what the O6 does,
before running without restraints.


*By the way, how to place an fatty acid and some other organic molecule
into the same system? Any tips?*
Probably docking is the way to go, followed by as long an MD as you can
perform.

Actually the PDB file contains a string of oxygens that are much too close
together to be hydrogen bonded water molecules, though they've labelled
them as water oxygens. I'd guess that was some kind of lipid? It's strange.
If it was in fact a lipid I'd recommend you modify that to be whatever
fatty acid you need, rather than docking.

Best,

Oliver

**Comment by Lachele** [comment] 2019-05-21 15:14
One minor but important addition to Oliver's instructions:  the glucose residues on the non-reducing termini will need to be 0GA (that's zero-G-A).  And, on the reducing end you'll need to change the aglycon to whatever it is... hang on... checking... looks like probably just an OH, so you will need to make that a separate residue named ROH.  

I would probably remove all the hydrogens and let Leap add them back in, if you're using leap.

We're working on code that will automatically rename atoms and residues like that.

**Comment by Lachele** [comment] 2019-05-21 17:37
I take it back.  Oliver is right: all 4GA.  I didn't realize those were big cycles.  His warnings about the weird oxygens are worth heeding.  

I can't look at the paper right now.  Are you wanting to start with the 1c58 structure and graft on some NeuNAc residues?  Are you wanting to change some residues from glucose to something else?   Either way, that can be done.  For something that large, having an existing structure (like 1c58) to start with will make things a lot simpler.  You can also build it 'from scratch', but you'll have an easier time if you start from a structure like 1c58.  

Doing this sort of thing is definitely a question for our mailing list.  Oliver and I can do these things, but it's good to have more people available to answer.

**Comment by pslacerda** [comment] 2019-05-22 05:38
Wow, great directions to follow. I'll talk soon with my coworker about all this. I wasn't even aware about reducing terminals and large cycles, thank you!

Such software that does such kind of renaming would enable some of us to do some simulations.

Our system is the plain CA26 bounded to some compounds, the idea is rank them by interaction strength. Now I'm thinking about simulate the carbohydrate using the 1C58 structure to figure out prevalent conformations (and resolve the O6 positions) so we can dock the compounds into it, get some coherent poses and then start steered simulations to have our rank by how long it takes to undock the compound.

The Amber manual says that maybe TIP5P is a good water model for Glycam, do you know something about? When I talk to my coworker we'll find what those oxygens are.

It's a long journey until there, I hope to collect the information we need, stablish a plan and then do the simulations. The question about the linked sialic acid was more of a curiosity. I'm was also dreaming about increase the temperature to disorder the system and then cool down so eventually it would fold with a realistic pose docked, but seems too much for now.

For now is just rename the atoms, tleap into Amber and see what we got.

**Comment by pslacerda** [comment] 2019-05-29 20:08
Hi,

We simply renamed GLC to 4CA and some oxygen bound hydrogens and tleap loaded nice with TIP3P. Now I'm doing preliminary simulations to find if there are any other challenges. Everything seems ok.

Despite I choose the standard parameter set, I'm in doubt about the extra points models. How can I place such atoms and what it is supposed to do?

I have no idea why the AmberTools cmake script didn't worked for me. Also don't know about the weird oxygens you are talking about.

**Comment by gitoliver** [comment] 2019-05-30 07:06
Hi Pedro,

The residue name should be 4GA not 4CA! When loading tip3p in tleap you can
instead load tip5p, you don't need to place anything manually. Here are the
relevant tleap commands:
loadAmberParams frcmod.tip5p
etc.
solvatebox mol TIP5PBOX 10.0 1.0

We've found GLYCAM performs better in reproducing a number of experimental
properties when the water model is TIP5P. This is just a number of
observations, I don't have any literature to hand. In your application
TIP3P may be fine, but as always you should have some experimental
observables you are comparing to for validating the model.

Best,


Oliver

**Comment by pslacerda** [comment] 2019-05-30 07:54
Hi Oliver,

It was 4GA indeed! So TIP5P for next round.

We have some experimental data related to temperature variation and ligand inclusion, and are looking forward to validate on it.

The amylose quickly unfolded from that beautiful conformation. It was just what for proteins would be called equilibration, but for CA26 was enough to drastically change the conformation. I'm hoping that after docking with AutoDock that cycles get preserved. I read that glucose ring conformations and oxygen bonds are the main determinants of the structure, but I'm unsure about how to measure the stability of them (like RMSD of alpha carbons in proteins).

Extra water points for now. And what about the GLYCAM06 extra points? It is also just a better and slower model (maybe even compatible with TIP5P)?

So far so noob, I'm very thankful.

Best,
Pedro

**Comment by pslacerda** [comment] 2019-06-07 11:45
Even wit a lot of room to improvements we got it working. No need for gmml or gems, GLYCAM is already embedded into Amber.

I'm not closing this issue because I think that includes and general build are still messed up outside docker.

Carbs are a very different than protein in respect of molecular dynamics. We are having a lot of fun.

Best regards

**Comment by gitoliver** [comment] 2019-06-07 12:07
Pedro, I missed your last message. During equilibration of the properties of your system like pressure and volume you should hold the glycan in position with Cartesian restraints. The box resizing can put significant unnatural forces on a solute. The water that you add is crystalline and tleap leaves gaps between the solute and water that need to be filled. Don't do MD with unrestrained solute until your temp, pressure and volume have equilibrated.  

> And what about the GLYCAM06 extra points?
 You could use it. It hasn't been employed much. I'm not 100% sure, but I believe the reason was that there wasn't an equivalent AMBER EP forcefield at the time, while for glycans in solution GLYCAM06 with TIP3P was shown to perform just fine.

> glucose ring conformations and oxygen bonds are the main determinants of the structure
Glucose ring should remain a 4C1 unless there is a good reason for it not to be (like being in an enzyme active site). The 1-4 interglycosidic linkages have some flexibility. You can look up what is normal and compare with what is in your simulation.

I can't reproduce the problem you are having with the stable branch. I'm able to pull and compile just fine.

Let's move further MD discussion to the mailing list, as others might find it useful and won't find it here. You just enter your name and email:
https://listserv.uga.edu/cgi-bin/wa?SUBED1=GLYCAM-L&A=1
Takes a few seconds.

**Closed as completed** 2022-03-10 10:49 UTC
